In [5]:
import numpy as np

### numpy array

In [1]:
myList = [20, 30, 40]

In [3]:
myList

[20, 30, 40]

In [6]:
np.array(myList)

array([20, 30, 40])

In [8]:
yeniDizi = np.random.randint(1, 100 , 5)

In [9]:
yeniDizi

array([96, 33,  8, 13, 99])

In [10]:
yeniDizi > 20

array([ True,  True, False, False,  True])